version: '3'
networks:
  default:
    driver: bridge
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: pelias_libpostal
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:${PELIAS_LIBPOSTAL_PORT:-4400}:4400" ]
  schema:
    image: pelias/schema:master
    container_name: pelias_schema
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
  api:
    image: pelias/api:master
    container_name: pelias_api
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=${PELIAS_API_PORT:-4000}" ]
    ports: [ "0.0.0.0:${PELIAS_API_PORT:-4000}:${PELIAS_API_PORT:-4000}" ]
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
  placeholder:
    image: pelias/placeholder:master
    container_name: pelias_placeholder
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=${PELIAS_PLACEHOLDER_PORT:-4100}" ]
    ports: [ "127.0.0.1:${PELIAS_PLACEHOLDER_PORT:-4100}:${PELIAS_PLACEHOLDER_PORT:-4100}" ]
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
      - "./${peliasRegion}/blacklist/:/data/blacklist"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
      - "./${peliasRegion}/blacklist/:/data/blacklist"
  openstreetmap:
    image: pelias/openstreetmap:master
    container_name: pelias_openstreetmap
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
      - "../${peliasRegion}/blacklist/:/data/blacklist"
  openaddresses:
    image: pelias/openaddresses:master
    container_name: pelias_openaddresses
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
      - "./${peliasRegion}/blacklist/:/data/blacklist"
  geonames:
    image: pelias/geonames:master
    container_name: pelias_geonames
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
      - "./${peliasRegion}/blacklist/:/data/blacklist"
  transit:
    image: pelias/transit:master
    container_name: pelias_transit
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
  csv-importer:
    image: pelias/csv-importer:master
    container_name: pelias_csv_importer
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
      - "./${peliasRegion}/blacklist/:/data/blacklist"
  polylines:
    image: pelias/polylines:master
    container_name: pelias_polylines
    user: "${DOCKER_USER}"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
  interpolation:
    image: pelias/interpolation:master
    container_name: pelias_interpolation
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=${PELIAS_INTERPOLATION_PORT:-4300}" ]
    ports: [ "127.0.0.1:${PELIAS_INTERPOLATION_PORT:-4300}:${PELIAS_INTERPOLATION_PORT:-4300}" ]
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
  pip:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=${PELIAS_PIP_PORT:-4200}" ]
    ports: [ "127.0.0.1:${PELIAS_PIP_PORT:-4200}:${PELIAS_PIP_PORT:-4200}" ]
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/${DATA_DIR}:/data"
  elasticsearch:
    image: pelias/elasticsearch:7.17.27
    container_name: pelias_elasticsearch
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:${PELIAS_ELASTIC_PORT:-9200}:9200", "127.0.0.1:${PELIAS_ELASTIC_NODE_PORT:-9300}:9300" ]
    volumes:
      - "./${peliasRegion}/${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
  fuzzy-tester:
    image: pelias/fuzzy-tester:master
    container_name: pelias_fuzzy_tester
    user: "${DOCKER_USER}"
    restart: "no"
    command: "--help"
    volumes:
      - "./${peliasRegion}/pelias.json:/code/pelias.json"
      - "./${peliasRegion}/test_cases:/code/pelias/fuzzy-tester/test_cases"
