FROM pelias/interpolation:master
COPY ./docker-pelias.json /code/pelias.json
COPY ./openstreetmap /data/openstreetmap
COPY ./openaddresses /data/openaddresses
COPY ./tiger /data/tiger
COPY ./interpolation /data/interpolation
COPY ./polylines /data/polylines
USER 0:0 
RUN chown 1000:1000 -R /data
USER 1000:1000
