FROM pelias/placeholder:master
COPY ./docker-pelias.json /code/pelias.json
COPY ./whosonfirst /data/whosonfirst
COPY ./placeholder /data/placeholder
USER 0:0 
RUN chown 1000:1000 -R /data
USER 1000:1000
